app_id: learning-angular
name: Learning Angular
description: Angular learning application

build:
  type: npm
  command: npm run build -- --configuration production
  working_directory: .
  output_dir: dist/Learning_Angular/browser

publish:
  type: static
  paths:
    - source: dist/Learning_Angular/browser
      destination: /